services:
  - type: web
    name: school21-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /api/ping

